version: "2"
services:
  react:
    build: .
    env_file: .env
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    ports:
      - "3000:3000"
    command:
      [ "yarn", "start" ]
